
services:
  web:
    build: .
    container_name: fastapi_container
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000" 
    depends_on:
      - db  
    restart: always


  db:
    image: postgres:15-alphine
    container_name: db_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    restart: always








volumes:
  pg_data: